import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import client from '../apolloClient'
import { gql } from '@apollo/client';
import Link from 'next/link';

export default function Home({ posts }) {
  console.log(posts)
  return (
    <div>
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Prueba de GraphCMS</h1>
      <ul>
        {
          posts?.map((post, i) => (
            <li key={i}>
              <Link href={`/posts/${post.slug}`}>
                <a>{post.title}</a>
              </Link>
            </li>
          ))
        }
      </ul>
      
    </div>
  )
}

export async function getStaticProps(){
  const {data} = await client.query({
    query: gql`
      query {
        posts {
          id
          title
          slug
          description
          content {
            raw
          }
          coverImage {
            url
          }
        }
      }
    `
  })

  const {posts} = data;

  return {
      props: {
        posts
      }
  }
}
